apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins-eks
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-jenkins
  resources:
    requests:
      storage: 10Gi
