apiVersion: v1
kind: Service
metadata:
  name: jenkins #name of the Jenkins Kubernetes Service
  namespace: jenkins
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:{region}:{user id}:certificate/{id}
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer #Type of the Jenkins Kubernetes Service
  ports:
  - port: 8080 #port for the Jenkins Kubernetes Service
    targetPort: 8080 #port for the Jenkins pod
  selector:
    app: jenkins
~                  
